### ISSUE TITLE
Is there any difference with PaperMod theme?

### ISSUE THREAD

**Issue by EricKwan2014** [nanxiaobei/hugo-paper#85]
As I saw the layout is look very similar with the following theme
See @https://github.com/adityatelange/hugo-PaperMod/

Would like to know any difference or is it just a plagiarism?
@RealA10N

**Comment by kdkasad** [comment]
The Hugo PaperMod theme, developed by @adityatelange, is a fork of this theme, @nanxiaobei didn't want to make this theme too complicated, so Aditya created a fork, where he, as well as other contributors, have added more features.

I wouldn't call it plagiarism. Hugo PaperMod started off with the same codebase (and still shares much of the code). It simply has had extra features added which were never included in this theme in order to keep it simple.

**Comment by EricKwan2014** [comment]
@kdkasad get it, thank you so much :D

**Comment by nanxiaobei** [comment]
> The Hugo PaperMod theme, developed by @adityatelange, is a fork of this theme, @nanxiaobei didn't want to make this theme too complicated, so Aditya created a fork, where he, as well as other contributors, have added more features.
> 
> I wouldn't call it plagiarism. Hugo PaperMod started off with the same codebase (and still shares much of the code). It simply has had extra features added which were never included in this theme in order to keep it simple.

Thanks for your explanation. ❤️
